ApolloTVofficial/Claws

.env.dist
index.js
package-lock.json
package.json
public/index.html
server.js
src/api/searchRoutes.js
src/scrapers/providers/tv/GoWatchSeries.js
src/scrapers/providers/tv/Series8.js
src/scrapers/providers/tv/SeriesFree.js
src/scrapers/resolvers/Streamango.js
src/scrapers/resolvers/resolve.js
src/utils/createEvent.js
src/utils/index.js
src/utils/logger.js

- During development, inject the client secret into the html using `ejs`.
- logger.js: don't include the filesystem logger when running in client mode.
- Only send the scrape event when running in server mode.
- Scraper bug fixes and general improvements. It now fails gracefully when it's unable to resolve certain links, no more pollution of the console logs with null-pointer exceptions.
- Also fixed an issue with the event-source leaking because `res.end()` wasn't called.
Once this is merged, your server will need to specify `CLAWS_ENV="server"` in its `.env` file to keep working as expected.

Add support for running in "client" mode, and minor fixes

---

src/api/resolveLinks.js
src/scrapers/providers/index.js

Add `MasterAnime` to the `universal` providers **(temporarily)** and add logic to add anime providers only if `anime` is sent as `type` from the client.
- Refactor logic in `resolveLinks.js` to do as described with staff:
> Use Anime, TV/Movie and Universal providers if the show / movie is Anime.
> Use TV/Movie and Universal providers is show / movie is not Anime.
- Add `MasterAnime` to Universal providers for now (temporary - see note)
As the client is not set up to currently send `anime` to Claws, when an anime show is currently searched, no links are returned. This is because Claws was only adding `MasterAnime` as a source if `anime` was sent as type. The only types currently sent by the client are `tv` / `movie`.
To fix this, and return links for anime shows until a `type:anime` is …

feature(provider): temporarily add MasterAnime as universal provider

---

src/scrapers/providers/BaseProvider.js
src/scrapers/providers/index.js
src/scrapers/providers/tv/Series8.js
src/utils/index.js

Update Series8 to use the BaseProvider class.
- Refactor the `Series8 ` provider to use the `BaseProvider` class.
- Add logging functionality into `BaseProvider` to be used by adding`this.logger.<level>`
- Add new util functions:
> removeYearFromTitle: remove year from a show title, ie: title (2019) -> title
> getClientIp: returns client ip from `req` object in a formatted way for requests.

refactor(series8): update series8 to use BaseProvider class

---

public/index.html
src/scrapers/providers/index.js
src/scrapers/providers/tv/SwatchSeries.js

Update SwatchSeries to use the BaseProvider class.
- Refactor the `SwatchSeries  ` provider to use the `BaseProvider` class.
- Add `year` field to the test html page.

refactor(swatchseries): refactor swatchseries to  follow BaseProvider structure

---

src/scrapers/providers/tv/SeriesFree.js

Fix console error:
`url is not defined`
This error was happening in some cases, and when it did, the `done` event failed to send as there was an error in the promise resolution.

fix(seriesfree): url is not defined

---

src/scrapers/providers/movies/bfmovies.js

Update BFMovies debug log to use correct logger.
- Change `logger` to `this.logger` in debug log.

fix(BFMovies): fix logger in BFMovies

---

src/scrapers/providers/BaseProvider.js

Cleanup BaseProvider variable name, add some instance variables that can be re-used across other providers in a cleaner way.
- Rename `sse` to `ws` in `BaseProvider` class.
- Add `randomUserAgent`, `rp` and `clientIp` to `BaseProvider` to allow for better reuse within other providers.

feat(baseprovider): small baseprovider improvements

---

src/api/resolveLinks.js

All providers are now reworked to extend BaseProvider, and all future ones should follow that

resolveLinks: Remove old-style provider support

---

package-lock.json
package.json
public/index.html
src/api/resolveLinks.js
src/scrapers/providers/BaseProvider.js
src/scrapers/providers/archive/anime/MasterAnime.js
src/scrapers/providers/movies/Afdah.js
src/scrapers/providers/movies/GoStream.js
src/scrapers/providers/movies/MovieFiles.js
src/scrapers/providers/movies/bfmovies.js
src/scrapers/providers/tv/AfdahTV.js
src/scrapers/providers/tv/GoWatchSeries.js
src/scrapers/providers/tv/SeriesFree.js
src/scrapers/providers/universal/123movie.js
src/scrapers/providers/universal/5movies.js
src/scrapers/resolvers/AfdahTV.js
src/scrapers/resolvers/_BaseResolver.js
src/scrapers/resolvers/resolve.js
src/utils/WsWrapper.js
src/utils/createEvent.js
src/utils/eventEmitter.js
src/utils/ffprobe.js
tests/resolvers/Mp4Upload.js
tests/resolvers/StreamLewd.js
tests/resolvers/TikiWiki.js

Naming fixes:
sse => ws
isDownload => isStreamable
provider <=> source
Fixed GoWatchSeries class name
Added SeriesFree class name
Added:
ffprobe logic (commented out right now until we figure out consistency)
HEAD request info
WsWrapper: encapsulates filter logic and file/HEAD info
Removed:
`getDataKind` because we're getting `content-type` from the HEAD request

Client scrape options

---

public/index.html

- Add placeholder "image" when the tmdb doesn't have a poster, rather than 404ing.

Dev ui : Add placeholder image when there's no poster.

---

package.json
src/api/authRoutes.js

Kamino uses NTP time now for authentication token. Thus, Claws needs to as well to compare and match the token appropriately. This should prevent a `401` on `/api/v1/login`.

Use NTP Time (Auth)

---

src/scrapers/resolvers/RapidVideo.js
src/scrapers/resolvers/resolve.js

Updated the RapidVideo resolver to actually retrieve the video source as well as getting different quality links.
- Retrieve video source using the `video` tag and then `source`.
- Have the RapidVideo resolver return an array of links instead because the page may contain different qualities.

fix(RapidVideo): get all available links from resolver

---

src/scrapers/providers/index.js
src/scrapers/providers/universal/Series9.js

Added Series9 as a new universal provider. Everything is pretty straight forward, I'll add the `testing required` tag for now as well as request a review.

feat(provider) add Series9 universal provider

---

src/scrapers/providers/universal/SolarMovie.js

As @kevincosmos found out, 5Movies essentially will ban access to them after time. Which means there is no point having 5Movies as an alternate URL in the SolarMovie provider. I left a comment just for reference in case there is some sort of bypass implemented in the future.

fix(provider) remove 5Movies due to access ban

---

public/ui/index.html

Essentially for the beta server, can't use the hard coded host as @j0j00 pointed out. Pulled out the relevant lines from his Heroku PR #55. This should allow access to the beta server's web interface now.

fix(web-interface) use dynamic websocket host

---

src/api/authRoutes.js

It seems Kamino has issues connecting to NTP servers on some cell phone providers.
Perhaps they (inadvertently) block them?
This endpoint gets around that.

Add route to get NTP from Claws.

---

src/utils/WsWrapper.js

Due to the recent bug where we're losing `scrape` event data, the HEAD request for those events need to be done on the client side. Thus, from Claws this should ensure we skip trying to do head request if the result is from a `scrape` event by checking the `isResultOfScrape` boolean.

fix(WsWrapper) update setHeadInfo() to check for isResultOfScrape

---

src/scrapers/providers/rd/universal/DDLSpot.js

So search was failing with any title with a colon in it because the results don't contain them. This just gets rid of any colons during search. The example I was looking at was `Avengers: Infinity War`. With this changes, it now works successfully!

DDLSpot Handle Colons

---

package-lock.json
package.json
src/scrapers/providers/BaseProvider.js
src/scrapers/providers/index.js
src/scrapers/providers/movies/LavinMovie.js
src/utils/constants.js
src/utils/queue.js

Essentially testing out if we can bypass the Cloudflare (CF) pages to expand what providers we could use. This uses the `cloudscraper`. It seems to be working. Part of the way I tested it in the early stage was by making a request to Kiss Anime's home page as it always goes through CF process. Using `request-promise` the page errors out. Replacing `_createRequest(...)` calls with `_createCloudflareRequest(...)`  however successfully loads the page and can see the resulting HTML. Will continue to test and modify the code for a bit, however this is not complicated at all so most time will probably be spent on testing to ensure it's working as expected.
- Added LavinMovie provider
Currently this doesn't have the Kue logic like `_createRequest(...)` does.

Cloudflare Bypass

---

src/scrapers/providers/movies/AZMovies.js
src/scrapers/providers/movies/BFMovies.js
src/scrapers/resolvers/RapidVideo.js
src/scrapers/resolvers/XStreamCDN.js
src/utils/index.js

- Updated the quality utility function to return integer values as noted in #121 
- Now uses regex to check for the quality instead of string comparisons
- Added a method called `getNumericValue`to convert quality as a string to it's representative numeric value
- Updated RapidVideo to use `getNumericValue`
- Updated XStreamCDN to use `getNumericValue`
- AZMovies provider retrieves quality from the video page
This should not be pushed to the server until Kamino implements the conversion from integers to strings for quality, as it seems to drop sources if quality is an integer...

Update Quality Utility Function
